# Generated by Django 3.1.7 on 2021-03-27 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0002_penduduk'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparatur',
            name='tml',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aparatur',
            name='ttl',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
