# Generated by Django 3.1.7 on 2021-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0004_aparatur_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparatur',
            options={'ordering': ['-update']},
        ),
        migrations.AlterField(
            model_name='aparatur',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_aparatur/'),
        ),
    ]
