# Generated by Django 3.1.7 on 2021-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0005_auto_20210328_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparatur',
            name='gambar',
            field=models.ImageField(blank=True, default='gambar_aparatur/default.jpg', null=True, upload_to='gambar_aparatur/'),
        ),
    ]
