# Generated by Django 3.1.7 on 2021-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0008_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='judul',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
