# Generated by Django 3.1.7 on 2021-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0011_galeri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img10',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img8',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='img9',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_galeri/'),
        ),
    ]
