# Generated by Django 3.1.7 on 2021-04-03 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0016_profildesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisSur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.jenispel')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='profildesa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profildesa',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Pelayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.jenissur')),
                ('penduduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.penduduk')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
